news_summary_task:
  description: >
    Conduct a comprehensive search for the latest news on the company '{company}'.
    Analyze the gathered articles to identify significant developments and market sentiment
    (positive, negative, or neutral).
  expected_output: >
    A concise, bullet-pointed summary of the key news findings, including the top 3-5 headlines,
    an analysis of the overall sentiment, and a concluding sentence on the potential stock impact.

financial_analysis_task:
  description: >
    Using the stock ticker '{company_ticker}', perform a fundamental analysis of the company.
    First, retrieve the company's profile to understand its business.
    Then, pull its latest annual income statement to assess its financial performance.
  expected_output: >
    A two-part report:
    1.  **Company Overview:** A brief summary of the company's business, industry, and market cap.
    2.  **Financial Highlights:** A bulleted list of the key figures from the income statement, including
        Total Revenue, Gross Profit, and Net Income.

research_task:
  description: >
    Using the provided research query '{research_query}', search the knowledge base
    to find information about that specific investment strategy.
  expected_output: >
    A clear and concise explanation of the investment strategy found in the knowledge base,
    summarizing the key principles and citing the source document.

crypto_analysis_task:
  description: >
    Retrieve and summarize the latest market data for the cryptocurrency '{crypto_name}'.
  expected_output: >
    A concise summary including the current price, market cap, rank, and a brief description of the project.

economic_analysis_task:
  description: >
    Retrieve the latest data for the economic indicator '{indicator_name}'.
  expected_output: >
    A clear report stating the most recent value and date for the requested economic indicator.

global_market_analysis_task:
  description: >
    Retrieve the latest price quote for the market symbol '{market_symbol}'.
  expected_output: >
    A concise report with the latest price, change, and change percentage for the requested symbol.

crypto_historical_analysis_task:
  description: >
    Retrieve and summarize historical market data for the cryptocurrency '{coin_id}' over the past '{days}' days.
  expected_output: >
    A summary including the highest, lowest, and average price over the specified period.